# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

# LoginWindowController is a class, that describes our login window and all logic behind it.
from controllers.BaseController import BaseController
from models.EmailAccount import EmailAccount
from services.LoginService import LoginService


class LoginWindowController(BaseController):
    def __init__(self, viewHandler, emailManager):
        super(LoginWindowController, self).__init__(viewHandler, emailManager)

    # function used to set up the login window
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(424, 134)
        loginWindow.setMinimumSize(QtCore.QSize(424, 134))
        loginWindow.setMaximumSize(QtCore.QSize(666, 391))
        self.gridLayout_2 = QtWidgets.QGridLayout(loginWindow)
        self.gridLayout_2.setContentsMargins(20, 10, 20, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.emailAdressLabel = QtWidgets.QLabel(loginWindow)
        self.emailAdressLabel.setObjectName("emailAdressLabel")
        self.gridLayout.addWidget(self.emailAdressLabel, 0, 0, 1, 1)
        self.emailAdressField = QtWidgets.QLineEdit(loginWindow)
        self.emailAdressField.setObjectName("emailAdressField")
        self.gridLayout.addWidget(self.emailAdressField, 0, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(loginWindow)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordField = QtWidgets.QLineEdit(loginWindow)
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setObjectName("passwordField")
        self.gridLayout.addWidget(self.passwordField, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loginButton = QtWidgets.QPushButton(loginWindow)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.retranslateUi(loginWindow)
        self.errorLabel = QtWidgets.QLabel(loginWindow)
        self.errorLabel.setObjectName(u"errorLabel")
        self.errorLabel.setGeometry(QtCore.QRect(10, 190, 261, 16))
        self.loginButton.clicked['bool'].connect(lambda: self.createLoginThread())

    # function, that is used to name labels and window title.
    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Login"))
        self.emailAdressLabel.setText(_translate("loginWindow", "Email:"))
        self.passwordLabel.setText(_translate("loginWindow", "Password:"))
        self.loginButton.setText(_translate("loginWindow", "Login"))

    def createLoginThread(self):
        if self.checkFields():
            emailAccount = EmailAccount(self.emailAdressField.text(),
                                        self.passwordField.text())

            self.loginService = LoginService(emailAccount, self)
            self.loginService.started.connect(lambda: self.loginButton.setEnabled(False))
            self.loginService.finished.connect(lambda: self.loginButton.setEnabled(True))
            self.loginService.finished.connect(lambda: self.emailManagerAction(self.loginService.FLAG, emailAccount))
            self.loginService.start()

    def emailManagerAction(self, flag, emailAccount):
        if flag:
            self.emailManager.addEmailAccount(emailAccount)
            self.emailManager.accountDict[emailAccount.address] = emailAccount

    # checks if fields for email address and password aren't empty.
    def checkFields(self):
        if not self.emailAdressField.text():
            self.errorLabel.setText("Email Address field is empty!")
            return False

        if not self.passwordField.text():
            self.errorLabel.setText("Password field is empty!")
            return False

        return True

# if __name__ == "__main__":
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     loginWindow = QtWidgets.QDialog()
#     ui = Ui_loginWindow()
#     ui.setupUi(loginWindow)
#     loginWindow.show()
#     sys.exit(app.exec_())
