# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SendWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from controllers.BaseController import BaseController


class SendWindowController(BaseController):
    def __init__(self, viewHandler):
        super(SendWindowController, self).__init__(viewHandler)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(586, 569)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.subjectField = QtWidgets.QLineEdit(Dialog)
        self.subjectField.setObjectName("subjectField")
        self.gridLayout.addWidget(self.subjectField, 1, 1, 1, 1)
        self.subjectLabel = QtWidgets.QLabel(Dialog)
        self.subjectLabel.setObjectName("subjectLabel")
        self.gridLayout.addWidget(self.subjectLabel, 1, 0, 1, 1)
        self.recipientField = QtWidgets.QLineEdit(Dialog)
        self.recipientField.setObjectName("recipientField")
        self.gridLayout.addWidget(self.recipientField, 0, 1, 1, 1)
        self.messageField = QtWidgets.QTextEdit(Dialog)
        self.messageField.setObjectName("messageField")
        self.gridLayout.addWidget(self.messageField, 2, 0, 1, 2)
        self.recipientLabel = QtWidgets.QLabel(Dialog)
        self.recipientLabel.setObjectName("recipientLabel")
        self.gridLayout.addWidget(self.recipientLabel, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.subjectLabel.setText(_translate("Dialog", "Subject:"))
        self.recipientLabel.setText(_translate("Dialog", "To:"))
