# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SendWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton

from controllers.BaseController import BaseController
from services.SendMessageService import SendMessageService


class SendWindowController(BaseController):
    def __init__(self, viewHandler, emailManager):
        super(SendWindowController, self).__init__(viewHandler)
        self.emailManager = emailManager

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(586, 569)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.recipientLabel = QtWidgets.QLabel(Dialog)
        self.recipientLabel.setObjectName("recipientLabel")
        self.gridLayout.addWidget(self.recipientLabel, 1, 0, 1, 1)
        self.subjectField = QtWidgets.QLineEdit(Dialog)
        self.subjectField.setObjectName("subjectField")
        self.gridLayout.addWidget(self.subjectField, 2, 1, 1, 1)
        self.recipientField = QtWidgets.QLineEdit(Dialog)
        self.recipientField.setObjectName("recipientField")
        self.gridLayout.addWidget(self.recipientField, 1, 1, 1, 1)
        self.messageField = QtWidgets.QTextEdit(Dialog)
        self.messageField.setObjectName("messageField")
        self.gridLayout.addWidget(self.messageField, 3, 0, 1, 2)
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.subjectLabel = QtWidgets.QLabel(Dialog)
        self.subjectLabel.setObjectName("subjectLabel")
        self.gridLayout.addWidget(self.subjectLabel, 2, 0, 1, 1)
        self.nameField = QtWidgets.QLineEdit(Dialog)
        self.nameField.setObjectName("nameField")
        self.gridLayout.addWidget(self.nameField, 0, 1, 1, 1)
        self.sendButton = QPushButton(Dialog)
        self.sendButton.setObjectName(u"sendButton")
        self.gridLayout.addWidget(self.sendButton, 4, 1, 1, 1)
        self.sendButton.clicked.connect(lambda: self.sendMessage())


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.recipientLabel.setText(_translate("Dialog", "To:"))
        self.nameLabel.setText(_translate("Dialog", "Name:"))
        self.subjectLabel.setText(_translate("Dialog", "Subject:"))
        self.sendButton.setText(_translate("Dialog", "Send"))

    def sendMessage(self):
        emailAccount = self.emailManager.accountDict[self.emailManager.emailAddress]
        name = self.nameField.text()
        to_emails = self.recipientField.text().split(', ')
        subject = self.subjectField.text()
        message = self.messageField.toPlainText()
        self.sendMessageService = SendMessageService(emailAccount, name, to_emails, subject, message)
        self.sendMessageService.start()





