# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SendWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controllers.BaseController import BaseController
from services.SendMessageService import SendMessageService


# Class, that describes window for sending messages and provides functionality to it.
class SendWindowController(BaseController):
    def __init__(self, viewHandler, emailManager):
        super(SendWindowController, self).__init__(viewHandler)
        self.emailManager = emailManager

    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(605, 576)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                                      QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(self.horizontalSpacer, 6, 2, 1, 1)
        self.sendButton = QtWidgets.QPushButton(Dialog)
        self.sendButton.setObjectName(u"sendButton")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.sendButton, 6, 3, 1, 1)
        self.recipientLabel = QtWidgets.QLabel(Dialog)
        self.recipientLabel.setObjectName(u"recipientLabel")
        self.gridLayout.addWidget(self.recipientLabel, 3, 0, 1, 1)
        self.errorLabel = QtWidgets.QLabel(Dialog)
        self.errorLabel.setObjectName(u"errorLabel")
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(2)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.errorLabel.sizePolicy().hasHeightForWidth())
        self.errorLabel.setSizePolicy(sizePolicy1)
        self.gridLayout.addWidget(self.errorLabel, 6, 0, 1, 2)
        self.nameField = QtWidgets.QLineEdit(Dialog)
        self.nameField.setObjectName(u"nameField")
        sizePolicy2 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(10)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.nameField.sizePolicy().hasHeightForWidth())
        self.nameField.setSizePolicy(sizePolicy2)
        self.gridLayout.addWidget(self.nameField, 0, 1, 1, 1)
        self.subjectField = QtWidgets.QLineEdit(Dialog)
        self.subjectField.setObjectName(u"subjectField")
        self.gridLayout.addWidget(self.subjectField, 4, 1, 1, 1)
        self.recipientField = QtWidgets.QLineEdit(Dialog)
        self.recipientField.setObjectName(u"recipientField")
        self.gridLayout.addWidget(self.recipientField, 3, 1, 1, 1)
        self.messageField = QtWidgets.QTextEdit(Dialog)
        self.messageField.setObjectName(u"messageField")
        self.gridLayout.addWidget(self.messageField, 5, 0, 1, 4)
        self.subjectLabel = QtWidgets.QLabel(Dialog)
        self.subjectLabel.setObjectName(u"subjectLabel")
        self.gridLayout.addWidget(self.subjectLabel, 4, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setObjectName(u"nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.sendButton.pressed.connect(lambda: self.sendMessage())
        self.retranslateUi(Dialog)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # function, that is used to name labels and window title.
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.recipientLabel.setText(_translate("Dialog", "To:"))
        self.nameLabel.setText(_translate("Dialog", "Name:"))
        self.subjectLabel.setText(_translate("Dialog", "Subject:"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.errorLabel.setText("")

    # function, that provides functionality for sending messages.
    def sendMessage(self):
        if self.checkFields():
            emailAccount = self.emailManager.accountDict[self.emailManager.emailAddress]
            name = self.nameField.text()
            recipient_text_list = [self.recipientField.text()]
            to_emails = self.recipientField.text().split(' ')

            if to_emails == recipient_text_list and len(to_emails) > 1:
                self.errorLabel.setText("Recipient field not properly written!")
            else:
                for i in range(len(to_emails)):
                    if to_emails[i][-1] == ',':
                        to_emails[i] = to_emails[i].replace(',', '')
                subject = self.subjectField.text()
                message = self.messageField.toPlainText()
                self.sendMessageService = SendMessageService(emailAccount, name, to_emails, subject, message)
                self.sendMessageService.started.connect(lambda: self.sendButton.setEnabled(False))
                self.sendMessageService.finished.connect(lambda: self.sendButton.setEnabled(True))
                self.sendMessageService.start()

# function, that checks fields in sending message window
    def checkFields(self):
        if not self.nameField.text():
            self.errorLabel.setText("Fill name field!")
            return False
        if not self.recipientField.text():
            self.errorLabel.setText("Fill recipient field!")
            return False
        if not self.subjectField.text():
            self.errorLabel.setText("Fill subject field!")
            return False

        return True
